### ISSUE TITLE
Add NAPIS ID field to client

### ISSUE THREAD

**Issue by brousch** [deafhhs/adapt#23]
ID is blank until assigned by NAPIS/WMAAA
size=11 char

**Comment by DanLindeman** [comment]
Implemented, max length 11 support 22-333-4444 NAPIS ID. Need to explore capitalization, as is currently displayed as "Napis id"

**Comment by DanLindeman** [comment]
with 300b1438b98be69b790f24af45274d448cf185bf napis id now displays "NAPIS ID"
